name: astro_env
channels:
  - conda-forge
  - defaults
dependencies:
  # Required dependencies
  - python>=3.11
  - astropy>=6.0
  - docstring_parser>=0.15
  - h5py>=3.7
  - numba>=0.57.0
  - numpy>=1.23
  - pyerfa>=2.0.1.1
  - pyyaml>=5.4.1
  - scipy>=1.9
  - setuptools_scm>=8.1
  - pyuvdata
  - tensorflow
  - tqdm
  - healpy

  # Optional dependencies
  - astropy-healpix>=1.0.2
  - astroquery>=0.4.4
  - hdf5plugin>=3.3.1
  - python-casacore>=3.5.2
  - camb

  # Additional tools (recommended)
  - pip
  - jupyter
  - matplotlib
  - ipython
  - joblib

  - pip:
      - lunarsky>=0.2.5
      - novas
      - novas_de405
      - git+https://github.com/christianhbye/21cmVAE.git@main#egg=VeryAccurateEmulator
      - git+https://github.com/telegraphic/pygdsm.git@master#egg=pygdsm